name: Python Lint Code Scanning Action
description: Runs a python linter of your choice, outputting SARIF
inputs:
  linter:
    description: 'The linter to use'
    required: true
    default: 'flake8'
    choices: ['ruff', 'flake8', 'pylint', 'mypy', 'pyright', 'pytype', 'fixit']
  target:
    description: 'The target to lint'
    required: true
    default: ${{ github.workspace }}
  output:
    description: 'The output file'
    required: false
    default: 'python_linter.sarif'
  python-version:
    description: 'The version of python to use'
    required: false
    default: '3.10'
    choices: ['3.11', '3.10', '3.9', '3.8', '3.7']
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Run Python Lint
      run: |
        echo "::notice::Using python version ${INPUT_PYTHON_VERSION}"
        if [[ "${OSTYPE}" == "msys" ]]; then
          PYTHON_CMD=python
        else
          PYTHON_CMD="python${INPUTS_PYTHON_VERSION}"
        fi
        linters=('ruff' 'flake8' 'pylint' 'mypy' 'pyright' 'pytype' 'fixit')
        install_flake8_formatter_linters=('ruff', 'flake8')
        if [[ "${linters[*]}" =~ (^|[^[:alpha:]])${INPUTS_LINTER}([^[:alpha:]]|$) ]]; then
          if [[ "${INPUTS_LINTER}" == "fixit" ]]; then
            "${PYTHON_CMD}" -mpip install "fixit >1" --pre || echo "::error::fixit 2 is not available for Python ${INPUTS_PYTHON_VERSION}"
          else
            "${PYTHON_CMD}" -mpip install "${INPUTS_LINTER}" || echo "::error::${INPUTS_LINTER} failed to install for Python ${INPUTS_PYTHON_VERSION}"
          fi
          if [[ "${install_flake8_formatter_linters[*]}" =~ (^|[^[:alpha:]])${INPUTS_LINTER}([^[:alpha:]]|$) ]]; then
            echo "::notice::installing flake8_sarif_formatter for ${INPUTS_LINTER}"
            "${PYTHON_CMD}" -mpip install "${GITHUB_ACTION_PATH}"/flake8_sarif_formatter
          fi

          "${PYTHON_CMD}" "${GITHUB_ACTION_PATH}"/python_lint.py "${INPUTS_LINTER}" --target="${INPUTS_TARGET}" --output="${GITHUB_WORKSPACE}/${INPUTS_OUTPUT}" || echo "::error::${INPUTS_LINTER} failed to run for Python ${INPUTS_PYTHON_VERSION}"
        else
          echo "::error::invalid linter ${INPUTS_LINTER}; choose one of ${linters[*]}"
        fi
      env:
        INPUTS_LINTER: ${{ inputs.linter }}
        INPUTS_TARGET: ${{ inputs.target }}
        INPUTS_OUTPUT: ${{ inputs.output }}
        INPUTS_PYTHON_VERSION: ${{ inputs.python-version }}
      shell: bash
    - name: Upload SARIF
      if: ${{ hashFiles(inputs.output) != '' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ inputs.output }}
