name: Python Lint Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '22 3 * * 2'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #linter: ['flake8', 'pylint', 'ruff', 'mypy', 'pytype', 'pyright', 'fixit']
        #python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        linter: ['flake8']
        python-version: ['3.11']
    steps:
      # install dependencies for all linters, then run the linter, so we don't get import failures whenthe linters scan the code
      - uses: actions/checkout@v4
      - name: Install pip dependencies
        run: |
          python3 -mpip install flake8 pylint ruff mypy pytype pyright fixit
          python3 -mpip install git+https://github.com/aegilops/flake8_sarif_formatter.git#egg=flake8-sarif-formatter
      - name: Run Python Lint
        uses: aegilops/python-lint-code-scanning-action@a1c703aa1acfa6fe0e241472817e7bc078772f66
        with:
          linter: ${{ matrix.linter }}
          python-version: ${{ matrix.python-version }}
