name: Python Lint Workflow
on:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [flake8, pylint, ruff, mypy, pytype, pyright, fixit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python Lint
        uses: aegilops/python-lint-code-scanning-action@main
        with:
          linter: ${{ matrix.linter }}
